package visionCore.dataStructures.tuples;

import java.io.Serializable;

/**
A tuple with 1 element.
This code was gracefully generated by a Python script.
@author	Deconimus
*/
public class Pointer <X> implements Serializable {
	
	private static final long serialVersionUID = 819498321351457541L;
	
	public X x;
	
	public Pointer() {}
	
	public Pointer(X x) {
		
		this.x = x;
	}
	
	@Override
	public boolean equals(Object o) {
		
		if (o == this) { return true; }
		if (o == null || !(o instanceof Pointer)) { return false; }
		
		Pointer t = (Pointer)o;
		
		return t.x.equals(x);
	}
	
}
