package visionCore.dataStructures.tuples;

import java.io.Serializable;

/**
A tuple with 2 elements.
This code was gracefully generated by a Python script.
@author	Deconimus
*/
public class Tuple <X, Y> implements Serializable {
	
	private static final long serialVersionUID = 350230888350855447L;
	
	public X x;
	public Y y;
	
	public Tuple() {}
	
	public Tuple(X x, Y y) {
		
		this.x = x;
		this.y = y;
	}
	
	@Override
	public boolean equals(Object o) {
		
		if (o == this) { return true; }
		if (o == null || !(o instanceof Tuple)) { return false; }
		
		Tuple t = (Tuple)o;
		
		return t.x.equals(x) && t.y.equals(y);
	}
	
}
